### ISSUE TITLE
error on master

### ISSUE THREAD

**Issue by gbasolu** [hydraplatform/hydra-server#12]
```bash
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
8 2018-08-13 14:20:12,276 - INFO - Connecting to database: mysql+mysqlconnector://root:Hydra2018!@172.20.0.10/basinit_1
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/base.py:528: SAWarning: Column 'name' on table <sqlalchemy.sql.selectable.Select at 0x7f48df831b38; Select object> being replaced by Column('name', String(length=60), table=<Select object>, nullable=False), which has the same key.  Consider use_labels for select() statements.
  (key, getattr(existing, 'table', None), value))
Traceback (most recent call last):
  File "run_server.py", line 40, in <module>
    start_cli()
  File "run_server.py", line 35, in start_cli
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "run_server.py", line 31, in run
    from hydra_server import s
  File "/app/hydra_server/__init__.py", line 306, in <module>
    s = HydraServer()
  File "/app/hydra_server/__init__.py", line 219, in __init__
    hdb.create_default_users_and_perms()
  File "/app/hydra-base/hydra_base/util/hdb.py", line 161, in create_default_users_and_perms
    perms = db.DBSession.query(Perm).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 79, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 622, in _populate_full
    populator(state, dict_, row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 1770, in load_collection_from_joined_new_row
    inst = _instance(row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 622, in _populate_full
    populator(state, dict_, row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 1806, in load_scalar_from_joined_new_row
    dict_[key] = _instance(row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 622, in _populate_full
    populator(state, dict_, row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 1770, in load_collection_from_joined_new_row
    inst = _instance(row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 622, in _populate_full
    populator(state, dict_, row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 1806, in load_scalar_from_joined_new_row
    dict_[key] = _instance(row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 611, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 902, in process
    value = bytes(value)
TypeError: string argument without an encoding

```

**Comment by knoxsp** [comment]
This is caused by a bug in the latest release of the mysql-connector-python library. I have updated hydra base to use 'mysqlclient' instead.
