### ISSUE TITLE
No module Mysqldb

### ISSUE THREAD

**Issue by gbasolu** [hydraplatform/hydra-server#13]
# Scenario
Connection library references moved from mysql-connector to mysql-client

# Problem
```shell
docker run -it --net hydra_net --ip 172.20.0.11 --env-file /home/giovanni/UoM/deployment/scripts/../config/d_hwi_1/env.list --name docker-hwi-run-1 -p 8181:8081 docker-hwi 
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
8 2018-08-13 17:33:22,333 - INFO - Connecting to database: mysql+mysqldb://root:Hydra2018!@172.20.0.10/basinit_1
Traceback (most recent call last):
  File "hwi/server.py", line 1, in <module>
    from hwi import app as application
  File "/app/hwi/__init__.py", line 30, in <module>
    connect()
  File "/app/hydra-base/hydra_base/db/__init__.py", line 69, in connect
    db_url = create_mysql_db(db_url)
  File "/app/hydra-base/hydra_base/db/__init__.py", line 57, in create_mysql_db
    tmp_engine = create_engine(no_db_url)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ModuleNotFoundError: No module named 'MySQLdb'
-- DONE ---
```

**Comment by knoxsp** [comment]
This error is caused by the 'mysqlclient' library not being installed.
This library is included in the latest version of hydra-base (master) setup script and requirements.txt
