### ISSUE TITLE
Location of spyne xml namespace has changed in Python3 release

### ISSUE THREAD

**Issue by pmslavin** [hydraplatform/hydra-server#2]
The `refactor` branch fails on startup under Python3 with...

```python
Traceback (most recent call last):
  File "./run_server.py", line 34, in <module>
    s.run_server(port=port)
  File "/home/paul/code/Hydra_py3/hydra-server/hydra_server/__init__.py", line 252, in run_server
    spyne.const.xml_ns.DEFAULT_NS = 'soap_server.hydra_complexmodels'
AttributeError: module 'spyne.const' has no attribute 'xml_ns'
```

This can be fixed by changing `spyne.const.xml_ns.DEFAULT_NS` to `spyne.const.xml.DEFAULT_NS`

**Comment by knoxsp** [comment]
see commit 8369fc2c6598bd73f08cefb02d1fb58a5f8f28c0
