### ISSUE TITLE
The DB is not created automatically

### ISSUE THREAD

**Issue by gbasolu** [hydraplatform/hydra-server#3]
```shell
4811 2018-07-17 12:18:34,735 - INFO - Connecting to database: mysql+mysqlconnector://root:Hydra2018!@localhost/basinit
Traceback (most recent call last):
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 176, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown database 'basinit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 674, in __connect
    connection = pool._invoke_creator(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 411, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/__init__.py", line 182, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 78, in __init__
    self.connect(**kwargs)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 736, in connect
    self._open_connection()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 179, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.ProgrammingError: 1049 (42000): Unknown database 'basinit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_server.py", line 19, in <module>
    from hydra_server import s
  File "/home/giovanni/UoM/hydra-server/hydra_server/__init__.py", line 46, in <module>
    connect()
  File "/home/giovanni/UoM/hydra-base/hydra_base/db/__init__.py", line 56, in connect
    DeclarativeBase.metadata.create_all(engine)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 674, in __connect
    connection = pool._invoke_creator(self)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 411, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/__init__.py", line 182, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 78, in __init__
    self.connect(**kwargs)
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 736, in connect
    self._open_connection()
  File "/home/giovanni/VirtualEnvs/venv3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 179, in _open_connection
    sqlstate=exc.sqlstate)
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1049 (42000): Unknown database 'basinit' (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by knoxsp** [comment]
See pull request on hydra-base repo:
https://github.com/hydraplatform/hydra-base/pull/40

**Comment by knoxsp** [comment]
This has been merged into hydra-base, and is now part of the normal operation of hydra
